wd: /data/exploratory/Users/jeff.alvarez/informatics_RNAseq_pipeline
fastqs: data/samples
samples:
        untreated: data/samples/untreated_1.fastq.gz
        dex: data/samples/dex_1.fastq.gz
        alb: data/samples/alb_1.fastq.gz
        alb_dex: data/samples/alb_dex_1.fastq.gz
ref: Human_B37.3
fa: data/Human_B37.3_chr1.fasta
gtf: data/Human_B37.3_chr1.gtf
