ID: 2020_04_13_B16
Title: "2020-04-13-B16"
HPC_ID:  jeff.alvarez
Contact_Name: "Jeff Alvarez"
Organism: "Mouse"
wd: /data/exploratory/Users/jeff.alvarez/omics-pipeline
fastqs: /data/exploratory/Users/jeff.alvarez/B16
samples:
        RNA1A: /data/exploratory/Users/jeff.alvarez/B16/RNA1A_1.fq.gz
        RNA2A: /data/exploratory/Users/jeff.alvarez/B16/RNA2A_1.fq.gz
        RNA3A: /data/exploratory/Users/jeff.alvarez/B16/RNA3A_1.fq.gz
        RNA4A: /data/exploratory/Users/jeff.alvarez/B16/RNA4A_1.fq.gz
        RNA5A: /data/exploratory/Users/jeff.alvarez/B16/RNA5A_1.fq.gz
        RNA6A: /data/exploratory/Users/jeff.alvarez/B16/RNA6A_1.fq.gz
        RNA7A: /data/exploratory/Users/jeff.alvarez/B16/RNA7A_1.fq.gz
        RNA8A: /data/exploratory/Users/jeff.alvarez/B16/RNA8A_1.fq.gz
ref:
        fa: /data/exploratory/Users/jeff.alvarez/pipeline_ins/Omicsoft.Mouse.B38.fasta
        gtf: /data/exploratory/Users/jeff.alvarez/pipeline_ins/Omicsoft.Mouse.B38.Ensembl.R78.gtf
        build: "Mouse.B38"
