ID: 2020_08_12_docker
Title: "2020-08-12 Docker"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /home/user/input/
ref:
        fa: /home/user/ref/Human_B37.3_chr1.fasta
        gtf: /home/user/ref/Human_B37.3_chr1.gtf
        build: Human_B37.3
known_sites: /home/user/ref/dbsnp_138.b37.chr_1.vcf.gz
