ID: 2020_09_23_NCI-H1703_ADAR
Title: "2020-09-23 NCI-H1703 ADAR"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /data/exploratory/rawData/internal/ADAR/NCI-H1703/
ref:
        fa: /data/exploratory/Users/jeff.alvarez/pipeline_ins/Omicsoft.Human.B37.3.fasta
        gtf: /data/exploratory/Users/jeff.alvarez/pipeline_ins/Omicsoft.Human.B37.3.OmicsoftGene20130723.gtf
        build: Human.B37.3
trimming:
        skip: false
known_sites: /data/exploratory/Users/jeff.alvarez/pipeline_ins/00-common_all.vcf.gz 
