ID: 2021_01_29_ADAR
Title: "2021-01-29 Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
samples: /data/exploratory/Users/jeff.alvarez/20210129_ADAR.txt
ref:
        fa: /data/exploratory/genome/hg19/hg19.fa
        gtf: /data/exploratory/genome/hg19/gencode.v19.annotation.gtf
        build: hg19
        known_sites: /data/exploratory/Users/jeff.alvarez/pipeline_ins/dbsnp_138.b37.with_chr.vcf.gz
